# Generated by Django 4.1.4 on 2023-09-23 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_sell_prod_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='money',
        ),
    ]
