# Generated by Django 4.1.4 on 2023-09-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_sell_address_remove_sell_cate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.CharField(max_length=255)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('money', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('cate', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Sell',
        ),
    ]
