# Generated by Django 4.1.4 on 2023-09-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_sells_prod_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('bookname', models.TextField()),
                ('usedyears', models.IntegerField()),
                ('money', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Sells',
        ),
    ]
